workflows:
  my-workflow:
    name: Build and Test
    instance_type: mac_mini_m1
    max_build_duration: 60

    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
        - name: "Build test"
          script: xcodebuild build -workspace "MyXcodeWorkspace.xcworkspace" -scheme "MyScheme" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - name@example.com

