workflows:
  my-workflow:
    name: Build and Test
    instance_type: mac_mini_m1
    max_build_duration: 60

    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"

    publishing:
      email:
        recipients:
          - name@example.com

