workflows:
  my-workflow:
    name: Build and Test
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      vars:
        RUBY_VERSION: "2.7.3"  # Versión de Ruby que necesitas
        BUNDLE_PATH: "vendor/bundle"  # Ruta para las gemas de Ruby
        BUNDLE_BIN: "$BUNDLE_PATH/bin"  # Ruta para los ejecutables de gemas

    cache:
      cache_paths:
        - ~/.pub-cache
        - vendor/bundle  # Cache para las gemas de Ruby

    scripts:
        - ls -l  # Listar archivos y directorios para verificar la presencia de Gemfile
        - gem install bundler  # Instalar Bundler si no está presente
        - bundle config set path 'vendor/bundle'  # Configurar la ruta de las gemas
        - bundle install  # Instalar gemas usando Bundler
        - bundle binstubs --all  # Generar binstubs para todas las gemas instaladas
        - bundle exec rake spec  # Ejecutar pruebas de Ruby (ajustar según sea necesario)

    artifacts:
      - "**/*.apk"  # Ejemplo de artefactos a almacenar, ajusta según tu proyecto

    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo "Publishing artifacts..."  # Script post-publicación opcional