workflows:
  my-workflow:
    name: Build and Test
    instance_type: mac_mini_m1
    max_build_duration: 60

    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build test
        script: 
          
          - gem install cocoapods  # Instala CocoaPods si no está instalado
          - pod install --repo-update  # Instala las dependencias de CocoaPods
          - xcodebuild build -workspace QRC.xcworkspace -scheme QRC CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - "QRC/build/**/*"  # Ajusta según la estructura de tu proyecto

    publishing:
      email:
        recipients:
          - name@example.com
      
      scripts:
        - echo "Publishing artifacts..."  # Script post-publicación opcional

