workflows:
  my-workflow:
    name: Build and Test
    instance_type: mac_mini_m1
    max_build_duration: 60

    scripts:
      - set -eo pipefail  # Asegura la terminación del script en caso de error
      - xcodebuild clean build -project QRC.xcodeproj -scheme QRC -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.3'  # Ejemplo de comando para compilar en Xcode

    artifacts:
      - build/**/outputs/*.ipa  # Ejemplo de artefactos a almacenar, ajusta según tu proyecto

    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo "Publishing artifacts..."  # Script post-publicación opcional